name: german_words
description: A new Flutter project to learn 1000 German words.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # SQLite
  sqflite: ^2.2.0
  
  path_provider: ^2.0.14
  
  provider: ^6.0.5

  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/words.json 